# Start from the official Jenkins LTS image
FROM jenkins/jenkins:lts-jdk11

# Switch to the root user to install packages
USER root

# Install prerequisites and the Docker client
RUN apt-get update && apt-get install -y curl
RUN curl -fsSL https://get.docker.com -o get-docker.sh
RUN sh get-docker.sh

# Switch back to the jenkins user
USER jenkins